//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TestDeliveryModel", "FK_RespondentTest_Test", "Respondent", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TestDelivery.DAL.Respondent), "Test", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestDelivery.DAL.Test), true)]
[assembly: EdmRelationshipAttribute("TestDeliveryModel", "FK_Test_TestTemplate", "TestTemplate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TestDelivery.DAL.TestTemplate), "Test", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestDelivery.DAL.Test), true)]

#endregion

namespace TestDelivery.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TestDeliveryEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TestDeliveryEntities object using the connection string found in the 'TestDeliveryEntities' section of the application configuration file.
        /// </summary>
        public TestDeliveryEntities() : base("name=TestDeliveryEntities", "TestDeliveryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestDeliveryEntities object.
        /// </summary>
        public TestDeliveryEntities(string connectionString) : base(connectionString, "TestDeliveryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestDeliveryEntities object.
        /// </summary>
        public TestDeliveryEntities(EntityConnection connection) : base(connection, "TestDeliveryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Respondent> Respondent
        {
            get
            {
                if ((_Respondent == null))
                {
                    _Respondent = base.CreateObjectSet<Respondent>("Respondent");
                }
                return _Respondent;
            }
        }
        private ObjectSet<Respondent> _Respondent;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Test> Test
        {
            get
            {
                if ((_Test == null))
                {
                    _Test = base.CreateObjectSet<Test>("Test");
                }
                return _Test;
            }
        }
        private ObjectSet<Test> _Test;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TestTemplate> TestTemplate
        {
            get
            {
                if ((_TestTemplate == null))
                {
                    _TestTemplate = base.CreateObjectSet<TestTemplate>("TestTemplate");
                }
                return _TestTemplate;
            }
        }
        private ObjectSet<TestTemplate> _TestTemplate;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Respondent EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRespondent(Respondent respondent)
        {
            base.AddObject("Respondent", respondent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Test EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTest(Test test)
        {
            base.AddObject("Test", test);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TestTemplate EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTestTemplate(TestTemplate testTemplate)
        {
            base.AddObject("TestTemplate", testTemplate);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestDeliveryModel", Name="Respondent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Respondent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Respondent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static Respondent CreateRespondent(global::System.Guid id, global::System.String name, global::System.String email)
        {
            Respondent respondent = new Respondent();
            respondent.Id = id;
            respondent.Name = name;
            respondent.Email = email;
            return respondent;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true, "PhoneNumber");
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true, "Url");
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true, "Notes");
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecretCode
        {
            get
            {
                return _SecretCode;
            }
            set
            {
                OnSecretCodeChanging(value);
                ReportPropertyChanging("SecretCode");
                _SecretCode = StructuralObject.SetValidValue(value, true, "SecretCode");
                ReportPropertyChanged("SecretCode");
                OnSecretCodeChanged();
            }
        }
        private global::System.String _SecretCode;
        partial void OnSecretCodeChanging(global::System.String value);
        partial void OnSecretCodeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestDeliveryModel", "FK_RespondentTest_Test", "Test")]
        public EntityCollection<Test> Tests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Test>("TestDeliveryModel.FK_RespondentTest_Test", "Test");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Test>("TestDeliveryModel.FK_RespondentTest_Test", "Test", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestDeliveryModel", Name="Test")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Test : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Test object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="respondentId">Initial value of the RespondentId property.</param>
        /// <param name="testId">Initial value of the TestId property.</param>
        /// <param name="secretCode">Initial value of the SecretCode property.</param>
        /// <param name="scorePercent">Initial value of the ScorePercent property.</param>
        public static Test CreateTest(global::System.Guid id, global::System.Guid respondentId, global::System.Guid testId, global::System.String secretCode, global::System.Int32 scorePercent)
        {
            Test test = new Test();
            test.Id = id;
            test.RespondentId = respondentId;
            test.TestId = testId;
            test.SecretCode = secretCode;
            test.ScorePercent = scorePercent;
            return test;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RespondentId
        {
            get
            {
                return _RespondentId;
            }
            set
            {
                OnRespondentIdChanging(value);
                ReportPropertyChanging("RespondentId");
                _RespondentId = StructuralObject.SetValidValue(value, "RespondentId");
                ReportPropertyChanged("RespondentId");
                OnRespondentIdChanged();
            }
        }
        private global::System.Guid _RespondentId;
        partial void OnRespondentIdChanging(global::System.Guid value);
        partial void OnRespondentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TestId
        {
            get
            {
                return _TestId;
            }
            set
            {
                OnTestIdChanging(value);
                ReportPropertyChanging("TestId");
                _TestId = StructuralObject.SetValidValue(value, "TestId");
                ReportPropertyChanged("TestId");
                OnTestIdChanged();
            }
        }
        private global::System.Guid _TestId;
        partial void OnTestIdChanging(global::System.Guid value);
        partial void OnTestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecretCode
        {
            get
            {
                return _SecretCode;
            }
            set
            {
                OnSecretCodeChanging(value);
                ReportPropertyChanging("SecretCode");
                _SecretCode = StructuralObject.SetValidValue(value, false, "SecretCode");
                ReportPropertyChanged("SecretCode");
                OnSecretCodeChanged();
            }
        }
        private global::System.String _SecretCode;
        partial void OnSecretCodeChanging(global::System.String value);
        partial void OnSecretCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateEmailSend
        {
            get
            {
                return _DateEmailSend;
            }
            set
            {
                OnDateEmailSendChanging(value);
                ReportPropertyChanging("DateEmailSend");
                _DateEmailSend = StructuralObject.SetValidValue(value, "DateEmailSend");
                ReportPropertyChanged("DateEmailSend");
                OnDateEmailSendChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateEmailSend;
        partial void OnDateEmailSendChanging(Nullable<global::System.DateTime> value);
        partial void OnDateEmailSendChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateStarted
        {
            get
            {
                return _DateStarted;
            }
            set
            {
                OnDateStartedChanging(value);
                ReportPropertyChanging("DateStarted");
                _DateStarted = StructuralObject.SetValidValue(value, "DateStarted");
                ReportPropertyChanged("DateStarted");
                OnDateStartedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateStarted;
        partial void OnDateStartedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateStartedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCompleted
        {
            get
            {
                return _DateCompleted;
            }
            set
            {
                OnDateCompletedChanging(value);
                ReportPropertyChanging("DateCompleted");
                _DateCompleted = StructuralObject.SetValidValue(value, "DateCompleted");
                ReportPropertyChanged("DateCompleted");
                OnDateCompletedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCompleted;
        partial void OnDateCompletedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateEvaluated
        {
            get
            {
                return _DateEvaluated;
            }
            set
            {
                OnDateEvaluatedChanging(value);
                ReportPropertyChanging("DateEvaluated");
                _DateEvaluated = StructuralObject.SetValidValue(value, "DateEvaluated");
                ReportPropertyChanged("DateEvaluated");
                OnDateEvaluatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateEvaluated;
        partial void OnDateEvaluatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateEvaluatedChanged();
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScorePercent
        {
            get
            {
                return _ScorePercent;
            }
            set
            {
                OnScorePercentChanging(value);
                ReportPropertyChanging("ScorePercent");
                _ScorePercent = StructuralObject.SetValidValue(value, "ScorePercent");
                ReportPropertyChanged("ScorePercent");
                OnScorePercentChanged();
            }
        }
        private global::System.Int32 _ScorePercent;
        partial void OnScorePercentChanging(global::System.Int32 value);
        partial void OnScorePercentChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestDeliveryModel", "FK_RespondentTest_Test", "Respondent")]
        public Respondent Respondent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Respondent>("TestDeliveryModel.FK_RespondentTest_Test", "Respondent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Respondent>("TestDeliveryModel.FK_RespondentTest_Test", "Respondent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Respondent> RespondentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Respondent>("TestDeliveryModel.FK_RespondentTest_Test", "Respondent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Respondent>("TestDeliveryModel.FK_RespondentTest_Test", "Respondent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestDeliveryModel", "FK_Test_TestTemplate", "TestTemplate")]
        public TestTemplate TestTemplate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TestTemplate>("TestDeliveryModel.FK_Test_TestTemplate", "TestTemplate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TestTemplate>("TestDeliveryModel.FK_Test_TestTemplate", "TestTemplate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TestTemplate> TestTemplateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TestTemplate>("TestDeliveryModel.FK_Test_TestTemplate", "TestTemplate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TestTemplate>("TestDeliveryModel.FK_Test_TestTemplate", "TestTemplate", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestDeliveryModel", Name="TestTemplate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TestTemplate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TestTemplate object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="timeLimit">Initial value of the TimeLimit property.</param>
        /// <param name="isQuestionTimeLimitEnforced">Initial value of the IsQuestionTimeLimitEnforced property.</param>
        /// <param name="isRandomOrder">Initial value of the IsRandomOrder property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        /// <param name="priority">Initial value of the Priority property.</param>
        public static TestTemplate CreateTestTemplate(global::System.Guid id, global::System.String name, global::System.Int32 timeLimit, global::System.Boolean isQuestionTimeLimitEnforced, global::System.Boolean isRandomOrder, global::System.Boolean isActive, global::System.Int32 priority)
        {
            TestTemplate testTemplate = new TestTemplate();
            testTemplate.Id = id;
            testTemplate.Name = name;
            testTemplate.TimeLimit = timeLimit;
            testTemplate.IsQuestionTimeLimitEnforced = isQuestionTimeLimitEnforced;
            testTemplate.IsRandomOrder = isRandomOrder;
            testTemplate.IsActive = isActive;
            testTemplate.Priority = priority;
            return testTemplate;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StartInstructions
        {
            get
            {
                return _StartInstructions;
            }
            set
            {
                OnStartInstructionsChanging(value);
                ReportPropertyChanging("StartInstructions");
                _StartInstructions = StructuralObject.SetValidValue(value, true, "StartInstructions");
                ReportPropertyChanged("StartInstructions");
                OnStartInstructionsChanged();
            }
        }
        private global::System.String _StartInstructions;
        partial void OnStartInstructionsChanging(global::System.String value);
        partial void OnStartInstructionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeLimit
        {
            get
            {
                return _TimeLimit;
            }
            set
            {
                OnTimeLimitChanging(value);
                ReportPropertyChanging("TimeLimit");
                _TimeLimit = StructuralObject.SetValidValue(value, "TimeLimit");
                ReportPropertyChanged("TimeLimit");
                OnTimeLimitChanged();
            }
        }
        private global::System.Int32 _TimeLimit;
        partial void OnTimeLimitChanging(global::System.Int32 value);
        partial void OnTimeLimitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsQuestionTimeLimitEnforced
        {
            get
            {
                return _IsQuestionTimeLimitEnforced;
            }
            set
            {
                OnIsQuestionTimeLimitEnforcedChanging(value);
                ReportPropertyChanging("IsQuestionTimeLimitEnforced");
                _IsQuestionTimeLimitEnforced = StructuralObject.SetValidValue(value, "IsQuestionTimeLimitEnforced");
                ReportPropertyChanged("IsQuestionTimeLimitEnforced");
                OnIsQuestionTimeLimitEnforcedChanged();
            }
        }
        private global::System.Boolean _IsQuestionTimeLimitEnforced;
        partial void OnIsQuestionTimeLimitEnforcedChanging(global::System.Boolean value);
        partial void OnIsQuestionTimeLimitEnforcedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsRandomOrder
        {
            get
            {
                return _IsRandomOrder;
            }
            set
            {
                OnIsRandomOrderChanging(value);
                ReportPropertyChanging("IsRandomOrder");
                _IsRandomOrder = StructuralObject.SetValidValue(value, "IsRandomOrder");
                ReportPropertyChanged("IsRandomOrder");
                OnIsRandomOrderChanged();
            }
        }
        private global::System.Boolean _IsRandomOrder;
        partial void OnIsRandomOrderChanging(global::System.Boolean value);
        partial void OnIsRandomOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value, "IsActive");
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value, "Priority");
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.Int32 _Priority;
        partial void OnPriorityChanging(global::System.Int32 value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EndInstructions
        {
            get
            {
                return _EndInstructions;
            }
            set
            {
                OnEndInstructionsChanging(value);
                ReportPropertyChanging("EndInstructions");
                _EndInstructions = StructuralObject.SetValidValue(value, true, "EndInstructions");
                ReportPropertyChanged("EndInstructions");
                OnEndInstructionsChanged();
            }
        }
        private global::System.String _EndInstructions;
        partial void OnEndInstructionsChanging(global::System.String value);
        partial void OnEndInstructionsChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestDeliveryModel", "FK_Test_TestTemplate", "Test")]
        public EntityCollection<Test> Tests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Test>("TestDeliveryModel.FK_Test_TestTemplate", "Test");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Test>("TestDeliveryModel.FK_Test_TestTemplate", "Test", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
