//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TestDelivery.DAL.Questions
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuestionsDao : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuestionsDao object using the connection string found in the 'QuestionsDao' section of the application configuration file.
        /// </summary>
        public QuestionsDao() : base("name=QuestionsDao", "QuestionsDao")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuestionsDao object.
        /// </summary>
        public QuestionsDao(string connectionString) : base(connectionString, "QuestionsDao")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuestionsDao object.
        /// </summary>
        public QuestionsDao(EntityConnection connection) : base(connection, "QuestionsDao")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Question> Questions
        {
            get
            {
                if ((_Questions == null))
                {
                    _Questions = base.CreateObjectSet<Question>("Questions");
                }
                return _Questions;
            }
        }
        private ObjectSet<Question> _Questions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Questions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuestions(Question question)
        {
            base.AddObject("Questions", question);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestDelivery.DAL.Questions", Name="FreeTextQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FreeTextQuestion : Question
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FreeTextQuestion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="summary">Initial value of the Summary property.</param>
        /// <param name="timeLimit">Initial value of the TimeLimit property.</param>
        /// <param name="score">Initial value of the Score property.</param>
        public static FreeTextQuestion CreateFreeTextQuestion(global::System.Guid id, global::System.String summary, global::System.Int32 timeLimit, global::System.Int32 score)
        {
            FreeTextQuestion freeTextQuestion = new FreeTextQuestion();
            freeTextQuestion.Id = id;
            freeTextQuestion.Summary = summary;
            freeTextQuestion.TimeLimit = timeLimit;
            freeTextQuestion.Score = score;
            return freeTextQuestion;
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestDelivery.DAL.Questions", Name="MultipleChoiceQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MultipleChoiceQuestion : Question
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MultipleChoiceQuestion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="summary">Initial value of the Summary property.</param>
        /// <param name="timeLimit">Initial value of the TimeLimit property.</param>
        /// <param name="score">Initial value of the Score property.</param>
        public static MultipleChoiceQuestion CreateMultipleChoiceQuestion(global::System.Guid id, global::System.String summary, global::System.Int32 timeLimit, global::System.Int32 score)
        {
            MultipleChoiceQuestion multipleChoiceQuestion = new MultipleChoiceQuestion();
            multipleChoiceQuestion.Id = id;
            multipleChoiceQuestion.Summary = summary;
            multipleChoiceQuestion.TimeLimit = timeLimit;
            multipleChoiceQuestion.Score = score;
            return multipleChoiceQuestion;
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestDelivery.DAL.Questions", Name="Problem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Problem : Question
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Problem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="summary">Initial value of the Summary property.</param>
        /// <param name="timeLimit">Initial value of the TimeLimit property.</param>
        /// <param name="score">Initial value of the Score property.</param>
        public static Problem CreateProblem(global::System.Guid id, global::System.String summary, global::System.Int32 timeLimit, global::System.Int32 score)
        {
            Problem problem = new Problem();
            problem.Id = id;
            problem.Summary = summary;
            problem.TimeLimit = timeLimit;
            problem.Score = score;
            return problem;
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestDelivery.DAL.Questions", Name="Question")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Problem))]
    [KnownTypeAttribute(typeof(FreeTextQuestion))]
    [KnownTypeAttribute(typeof(MultipleChoiceQuestion))]
    public abstract partial class Question : EntityObject
    {
        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, false, "Summary");
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, true, "Tags");
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags;
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeLimit
        {
            get
            {
                return _TimeLimit;
            }
            set
            {
                OnTimeLimitChanging(value);
                ReportPropertyChanging("TimeLimit");
                _TimeLimit = StructuralObject.SetValidValue(value, "TimeLimit");
                ReportPropertyChanged("TimeLimit");
                OnTimeLimitChanged();
            }
        }
        private global::System.Int32 _TimeLimit;
        partial void OnTimeLimitChanging(global::System.Int32 value);
        partial void OnTimeLimitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Score
        {
            get
            {
                return _Score;
            }
            set
            {
                OnScoreChanging(value);
                ReportPropertyChanging("Score");
                _Score = StructuralObject.SetValidValue(value, "Score");
                ReportPropertyChanged("Score");
                OnScoreChanged();
            }
        }
        private global::System.Int32 _Score;
        partial void OnScoreChanging(global::System.Int32 value);
        partial void OnScoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true, "Content");
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        #endregion

    }

    #endregion

}
